version: '3.8'
services:
    Frontend:
        image: gbarnacle79/blue-angular:7
        deploy:
            replicas: 2
        ports:
        - target: 8080
          published: 8080  

    Backend:
        image: fabriziodea/bluebackend:1
        deploy:
            replicas: 2
        ports:
        - target: 9966
          published: 9966 
