- name: copying file with playbook 
  copy:
    src: ~/bluescript.sh
    dest: /home/bluescript.sh
    mode: "777"
    owner: ubuntu


- name: Run our script
  ansible.builtin.shell:  /home/bluescript.sh
