---
# tasks for manager

  - name: Initialize docker swarm
    docker_swarm:
      state: present

  - name: Get the manager node join-token
    docker_swarm_info:
    register: swarm_info
    
  - name: Get join-token for manager nodes
    set_fact:
      join_token_manager: "{{ swarmanager.swarm_result.swarm_facts.JoinTokens.Worker }}"
