all:
  children:
    managers:
      hosts:
        {{ Manager_IP: }}
    workers:
      hosts:
        {{ Worker_IP: }}
    nginx:
      hosts:
        {{ NGINX_IP: }}

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/MyKeyPai.pem'
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
