all:
  children:
    swarmanager:
      hosts:
        ec2-54-195-22-78.eu-west-1.compute.amazonaws.com:
    swarmworker:
      hosts:
        ec2-54-216-192-207.eu-west-1.compute.amazonaws.com:
    nginx:
      hosts:
        ec2-34-244-159-11.eu-west-1.compute.amazonaws.com:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/porconekey.pem'
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
