- name: Setup Nginx (Load Balancer)
  hosts: nginx
  become: true
  roles:
    - nginx

- name: Install dependencies
  hosts: swarmanager, swarmworker
  become: true
  roles:
    - git
    - docker
    - nodejs
    - script
   
- name:  init swarm manager
  hosts: swarmanager
  become: true
  roles: 
   - swarm-init

- name: workers joins
  hosts: swarmworker
  become: true
  roles: 
   - swarm-worker

- name: manager deploys
  hosts: swarmanager
  become: true
  roles:
  - deploy
