- name: Setup Nginx (Load Balancer)
  hosts: nginx
  become: true
  roles:
    - nginx

- name: Install dependencies
  hosts: managers,workers
  become: true
  roles:
    - git
    - docker
    - nodejs
    - script

- name:  init swarm manager
  hosts: managers
  become: true
  roles: 
   - swarm-init

- name: workers joins
  hosts: workers
  become: true
  roles: 
   - swarm-worker

- name: manager deploys
  hosts: managers
  become: true
  roles:
  - deploy
